In [3]:
import pandas as pd

In [4]:
df_east = pd.read_excel('clubs_east.xlsx')

In [23]:
df_east['E/W'] = 'east'

In [3]:
df_west = pd.read_excel('clubs_west.xlsx')

In [22]:
df_west['E/W'] = 'west'

In [25]:
df = pd.concat([df_east, df_west], axis=0, join='outer', ignore_index= True)

In [26]:
df.head(30)

,Name,Years,Address,Postcode,E/W
0,Franz,1970 - 1997,Schönhauser Allee 36,10435,east
1,Knaack,1952 - 2010,Greifs­wal­der Straße 224,10245,east
2,Kreisjugendklub Pablo Neruda,1984 - 2010,Insel der Jugend,12435,east
3,Schoppenstube,1963 - 2013,Schönhauser Allee 44,10435,east
4,Abraxas,1984 - 2009,Kantstraße 134,10625,west
5,Café Swing,1982 - 2002,Nollendorf­platz 3-4,10777,west
6,Cheetah,1968 - 1983,Hasendheide 13,10967,west
7,Chez Romy Haag,1974 - 1983,Fug­ger­straße 33,10777,west
8,Dschungel,1978 - 1993,Nürnberger Straße 53,10789,west
9,Ex n Pop,1984 - 2016,Manstein­straße 14,10783,west
10,Linientreu,1982 - 2008,Budapes­ter Straße 42,10787,west
11,Loft,1981 - 1998,Nollendorfplatz 5,10777,west
12,Metropol,1977 - 2005,Nollendorfplatz 5,10777,west
13,Punkhouse,1977 - 1978,Kurfürs­ten­damm 156,10709,west
14,Quarter Latin,1972 - 1989,Potsda­mer Straße 96,10785,west
15,Risiko,1981 - 1986,Yorck­straße 48,10965,west
16,Trash,1982 - 2001,Ora­ni­en­platz 17,10999,west
17,UFO,1988 - 1990,Köpe­ni­cker Straße 6,10997,west

In [27]:
df[['Opening', 'Closing']] = df['Years'].str.split(" - ", expand=True)

In [30]:
df['City'] = "Berlin"

In [31]:
df

,Name,Years,Address,Postcode,E/W,Opening,Closing,City
0,Franz,1970 - 1997,Schönhauser Allee 36,10435,east,1970,1997,Berlin
1,Knaack,1952 - 2010,Greifs­wal­der Straße 224,10245,east,1952,2010,Berlin
2,Kreisjugendklub Pablo Neruda,1984 - 2010,Insel der Jugend,12435,east,1984,2010,Berlin
3,Schoppenstube,1963 - 2013,Schönhauser Allee 44,10435,east,1963,2013,Berlin
4,Abraxas,1984 - 2009,Kantstraße 134,10625,west,1984,2009,Berlin
5,Café Swing,1982 - 2002,Nollendorf­platz 3-4,10777,west,1982,2002,Berlin
6,Cheetah,1968 - 1983,Hasendheide 13,10967,west,1968,1983,Berlin
7,Chez Romy Haag,1974 - 1983,Fug­ger­straße 33,10777,west,1974,1983,Berlin
8,Dschungel,1978 - 1993,Nürnberger Straße 53,10789,west,1978,1993,Berlin
9,Ex n Pop,1984 - 2016,Manstein­straße 14,10783,west,1984,2016,Berlin
10,Linientreu,1982 - 2008,Budapes­ter Straße 42,10787,west,1982,2008,Berlin
11,Loft,1981 - 1998,Nollendorfplatz 5,10777,west,1981,1998,Berlin
12,Metropol,1977 - 2005,Nollendorfplatz 5,10777,west,1977,2005,Berlin
13,Punkhouse,1977 - 1978,Kurfürs­ten­damm 156,10709,west,1977,1978,Berlin
14,Quarter Latin,1972 - 1989,Potsda­mer Straße 96,10785,west,1972,1989,Berlin
15,Risiko,1981 - 1986,Yorck­straße 48,10965,west,1981,1986,Berlin
16,Trash,1982 - 2001,Ora­ni­en­platz 17,10999,west,1982,2001,Berlin
17,UFO,1988 - 1990,Köpe­ni­cker Straße 6,10997,west,1988,1990,Berlin

In [37]:
df['Address'] = df['Address'].str.strip()

In [44]:
for index, row in df.iterrows():
    address = f"{row['Address']},{row['Postcode']},{row['City']}"
    print(address)

Schönhauser Allee 36,10435,Berlin
Greifs­wal­der Straße 224,10245,Berlin
Insel der Jugend,12435,Berlin
Schönhauser Allee 44,10435,Berlin
Kantstraße 134,10625,Berlin
Nollendorf­platz 3-4,10777,Berlin
Hasendheide 13,10967,Berlin
Fug­ger­straße 33,10777,Berlin
Nürnberger Straße 53,10789,Berlin
Manstein­straße 14,10783,Berlin
Budapes­ter Straße 42,10787,Berlin
Nollendorfplatz 5,10777,Berlin
Nollendorfplatz 5,10777,Berlin
Kurfürs­ten­damm 156,10709,Berlin
Potsda­mer Straße 96,10785,Berlin
Yorck­straße 48,10965,Berlin
Ora­ni­en­platz 17,10999,Berlin
Köpe­ni­cker Straße 6,10997,Berlin

In [46]:
import geocoder

In [48]:
df['lat'] = None
df['lng'] = None

In [49]:

for index, row in df.iterrows():
    address = f"{row['Address']},{row['Postcode']},{row['City']}"
    g = geocoder.google(address, key=api_key)
    if g.latlng: 
        df.at[index, 'lat'] = g.latlng[0]
        df.at[index, 'lng'] = g.latlng[1]

df)

                            Name        Years                    Address  \
0                          Franz  1970 - 1997       Schönhauser Allee 36
1                         Knaack  1952 - 2010  Greifs­wal­der Straße 224
2   Kreisjugendklub Pablo Neruda  1984 - 2010           Insel der Jugend
3                  Schoppenstube  1963 - 2013       Schönhauser Allee 44
4                        Abraxas  1984 - 2009             Kantstraße 134
5                     Café Swing  1982 - 2002       Nollendorf­platz 3-4
6                        Cheetah  1968 - 1983             Hasendheide 13
7                 Chez Romy Haag  1974 - 1983          Fug­ger­straße 33
8                      Dschungel  1978 - 1993       Nürnberger Straße 53
9                       Ex n Pop  1984 - 2016         Manstein­straße 14
10                    Linientreu  1982 - 2008      Budapes­ter Straße 42
11                          Loft  1981 - 1998          Nollendorfplatz 5
12                      Metropol  1977 - 2005          Nollendorfplatz 5
13                     Punkhouse  1977 - 1978       Kurfürs­ten­damm 156
14                 Quarter Latin  1972 - 1989       Potsda­mer Straße 96
15                        Risiko  1981 - 1986            Yorck­straße 48
16                         Trash  1982 - 2001         Ora­ni­en­platz 17
17                           UFO  1988 - 1990      Köpe­ni­cker Straße 6

    Postcode   E/W Opening Closing    City        lat        lng
0      10435  east    1970    1997  Berlin  52.538305  13.412757
1      10245  east    1952    2010  Berlin  52.530379  13.425748
2      12435  east    1984    2010  Berlin  52.487222  13.480556
3      10435  east    1963    2013  Berlin  52.540398  13.412576
4      10625  west    1984    2009  Berlin  52.505844  13.315541
5      10777  west    1982    2002  Berlin  52.499428  13.352152
6      10967  west    1968    1983  Berlin   52.48756  13.421304
7      10777  west    1974    1983  Berlin  52.498983  13.342566
8      10789  west    1978    1993  Berlin  52.501722  13.338154
9      10783  west    1984    2016  Berlin  52.492545  13.367111
10     10787  west    1982    2008  Berlin   52.50537  13.337099
11     10777  west    1981    1998  Berlin  52.499001  13.352723
12     10777  west    1977    2005  Berlin  52.499001  13.352723
13     10709  west    1977    1978  Berlin  52.498721   13.30323
14     10785  west    1972    1989  Berlin  52.502085  13.364166
15     10965  west    1981    1986  Berlin  52.492989  13.367899
16     10999  west    1982    2001  Berlin  52.502312  13.416916
17     10997  west    1988    1990  Berlin  52.502272  13.440185

In [5]:
df.to_excel('clubs_east_west.xlsx', index=False)

NameError: name 'df' is not defined

In [6]:
df = pd.read_excel('clubs_east_west.xlsx')

In [7]:
df

,Name,Years,Address,Postcode,E/W,Opening,Closing,City,lat,lng
0,Franz,1970 - 1997,Schönhauser Allee 36,10435,east,1970,1997,Berlin,52.538305,13.412757
1,Knaack,1952 - 2010,Greifs­wal­der Straße 224,10245,east,1952,2010,Berlin,52.530379,13.425748
2,Kreisjugendklub Pablo Neruda,1984 - 2010,Insel der Jugend,12435,east,1984,2010,Berlin,52.487222,13.480556
3,Schoppenstube,1963 - 2013,Schönhauser Allee 44,10435,east,1963,2013,Berlin,52.540398,13.412576
4,Abraxas,1984 - 2009,Kantstraße 134,10625,west,1984,2009,Berlin,52.505844,13.315541
5,Café Swing,1982 - 2002,Nollendorf­platz 3-4,10777,west,1982,2002,Berlin,52.499428,13.352152
6,Cheetah,1968 - 1983,Hasendheide 13,10967,west,1968,1983,Berlin,52.487560,13.421304
7,Chez Romy Haag,1974 - 1983,Fug­ger­straße 33,10777,west,1974,1983,Berlin,52.498983,13.342566
8,Dschungel,1978 - 1993,Nürnberger Straße 53,10789,west,1978,1993,Berlin,52.501722,13.338154
9,Ex n Pop,1984 - 2016,Manstein­straße 14,10783,west,1984,2016,Berlin,52.492545,13.367111
10,Linientreu,1982 - 2008,Budapes­ter Straße 42,10787,west,1982,2008,Berlin,52.505370,13.337099
11,Loft,1981 - 1998,Nollendorfplatz 5,10777,west,1981,1998,Berlin,52.499001,13.352723
12,Metropol,1977 - 2005,Nollendorfplatz 5,10777,west,1977,2005,Berlin,52.499001,13.352723
13,Punkhouse,1977 - 1978,Kurfürs­ten­damm 156,10709,west,1977,1978,Berlin,52.498721,13.303230
14,Quarter Latin,1972 - 1989,Potsda­mer Straße 96,10785,west,1972,1989,Berlin,52.502085,13.364166
15,Risiko,1981 - 1986,Yorck­straße 48,10965,west,1981,1986,Berlin,52.492989,13.367899
16,Trash,1982 - 2001,Ora­ni­en­platz 17,10999,west,1982,2001,Berlin,52.502312,13.416916
17,UFO,1988 - 1990,Köpe­ni­cker Straße 6,10997,west,1988,1990,Berlin,52.502272,13.440185